import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components /Shared/Navbar";
import Footer from "@/Components /Shared/Footer";
import { CartProvider, CartDrawer } from "@/Components /Shared/Cart"; 
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>

<CartProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body>
          <Navbar />
          <Toaster />
          {children}
          <CartDrawer />
          <Footer />
        </body>
      </html>
    </CartProvider>


    </>
  );
}
